"""initial migration

Revision ID: 9118d7d18c36
Revises: 
Create Date: 2020-06-19 14:58:03.793041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9118d7d18c36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('availability_warehouse_id_fkey', 'availability', type_='foreignkey')
    op.drop_constraint('availability_product_id_fkey', 'availability', type_='foreignkey')
    op.create_foreign_key(None, 'availability', 'warehouse', ['warehouse_id'], ['warehouse_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'availability', 'product', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.add_column('customer', sa.Column('f_first_name', sa.String(length=20), nullable=True))
    op.drop_constraint('includes_order_id_fkey', 'includes', type_='foreignkey')
    op.create_foreign_key(None, 'includes', 'orders', ['order_id'], ['order_id'], ondelete='CASCADE')
    op.drop_constraint('order_item_order_id_fkey', 'order_item', type_='foreignkey')
    op.create_foreign_key(None, 'order_item', 'orders', ['order_id'], ['order_id'], ondelete='CASCADE')
    op.drop_constraint('order_item_warehouse_id_order_id_fkey', 'order_item_warehouse_id', type_='foreignkey')
    op.create_foreign_key(None, 'order_item_warehouse_id', 'orders', ['order_id'], ['order_id'], ondelete='CASCADE')
    op.drop_constraint('ordering_order_id_fkey', 'ordering', type_='foreignkey')
    op.create_foreign_key(None, 'ordering', 'orders', ['order_id'], ['order_id'], ondelete='CASCADE')
    op.drop_constraint('owns_customer_id_fkey', 'owns', type_='foreignkey')
    op.drop_constraint('owns_card_number_fkey', 'owns', type_='foreignkey')
    op.create_foreign_key(None, 'owns', 'customer', ['customer_id'], ['customer_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'owns', 'credit_card', ['card_number'], ['card_number'], ondelete='CASCADE')
    op.drop_constraint('paidwith_order_id_fkey', 'paidwith', type_='foreignkey')
    op.create_foreign_key(None, 'paidwith', 'orders', ['order_id'], ['order_id'], ondelete='CASCADE')
    op.drop_constraint('stock_product_id_fkey', 'stock', type_='foreignkey')
    op.create_foreign_key(None, 'stock', 'product', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.drop_constraint('stores_warehouse_id_fkey', 'stores', type_='foreignkey')
    op.drop_constraint('stores_product_id_fkey', 'stores', type_='foreignkey')
    op.create_foreign_key(None, 'stores', 'warehouse', ['warehouse_id'], ['warehouse_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'stores', 'product', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.drop_constraint('supplies_product_id_fkey', 'supplies', type_='foreignkey')
    op.drop_constraint('supplies_supplier_id_fkey', 'supplies', type_='foreignkey')
    op.create_foreign_key(None, 'supplies', 'product', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'supplies', 'supplier', ['supplier_id'], ['supplier_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplies', type_='foreignkey')
    op.drop_constraint(None, 'supplies', type_='foreignkey')
    op.create_foreign_key('supplies_supplier_id_fkey', 'supplies', 'supplier', ['supplier_id'], ['supplier_id'])
    op.create_foreign_key('supplies_product_id_fkey', 'supplies', 'product', ['product_id'], ['product_id'])
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.create_foreign_key('stores_product_id_fkey', 'stores', 'product', ['product_id'], ['product_id'])
    op.create_foreign_key('stores_warehouse_id_fkey', 'stores', 'warehouse', ['warehouse_id'], ['warehouse_id'])
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.create_foreign_key('stock_product_id_fkey', 'stock', 'product', ['product_id'], ['product_id'])
    op.drop_constraint(None, 'paidwith', type_='foreignkey')
    op.create_foreign_key('paidwith_order_id_fkey', 'paidwith', 'orders', ['order_id'], ['order_id'])
    op.drop_constraint(None, 'owns', type_='foreignkey')
    op.drop_constraint(None, 'owns', type_='foreignkey')
    op.create_foreign_key('owns_card_number_fkey', 'owns', 'credit_card', ['card_number'], ['card_number'])
    op.create_foreign_key('owns_customer_id_fkey', 'owns', 'customer', ['customer_id'], ['customer_id'])
    op.drop_constraint(None, 'ordering', type_='foreignkey')
    op.create_foreign_key('ordering_order_id_fkey', 'ordering', 'orders', ['order_id'], ['order_id'])
    op.drop_constraint(None, 'order_item_warehouse_id', type_='foreignkey')
    op.create_foreign_key('order_item_warehouse_id_order_id_fkey', 'order_item_warehouse_id', 'orders', ['order_id'], ['order_id'])
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.create_foreign_key('order_item_order_id_fkey', 'order_item', 'orders', ['order_id'], ['order_id'])
    op.drop_constraint(None, 'includes', type_='foreignkey')
    op.create_foreign_key('includes_order_id_fkey', 'includes', 'orders', ['order_id'], ['order_id'])
    op.drop_column('customer', 'f_first_name')
    op.drop_constraint(None, 'availability', type_='foreignkey')
    op.drop_constraint(None, 'availability', type_='foreignkey')
    op.create_foreign_key('availability_product_id_fkey', 'availability', 'product', ['product_id'], ['product_id'])
    op.create_foreign_key('availability_warehouse_id_fkey', 'availability', 'warehouse', ['warehouse_id'], ['warehouse_id'])
    # ### end Alembic commands ###
